# Generated by Django 5.0.4 on 2024-05-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='data',
        ),
        migrations.AlterField(
            model_name='viagem',
            name='chamado',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='iframe',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
