# Generated by Django 5.0.4 on 2024-05-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_viagem_data_alter_viagem_chamado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='lojas',
        ),
        migrations.AddField(
            model_name='viagem',
            name='lojas',
            field=models.ManyToManyField(blank=True, related_name='viagens', to='home.loja'),
        ),
    ]
