# Generated by Django 5.0.4 on 2024-05-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_viagem_suportes_viagem_suportes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
