# Generated by Django 5.0.4 on 2024-05-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_servico_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
