# Generated by Django 5.0.4 on 2024-05-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_servico_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='servicos',
        ),
        migrations.AddField(
            model_name='viagem',
            name='servicos',
            field=models.ManyToManyField(blank=True, null=True, related_name='servicos', to='home.servico'),
        ),
    ]
