# Generated by Django 5.0.4 on 2024-05-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_suporte_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='sigla',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
