# Generated by Django 5.0.4 on 2024-05-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_loja_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='suporte',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
