# Generated by Django 5.0.4 on 2024-05-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
