# Generated by Django 5.0.4 on 2024-05-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_senhausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suporte',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
