# Generated by Django 5.0.4 on 2024-06-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_loja_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='loja_mae',
            field=models.CharField(default='N/A', max_length=3),
        ),
        migrations.AlterField(
            model_name='suporte',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='suportes'),
        ),
        migrations.AlterField(
            model_name='suporte',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
