# Generated by Django 5.0.4 on 2024-06-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_loja_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suporte',
            name='imagem',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='suportes'),
        ),
    ]
