# Generated by Django 5.0.4 on 2024-06-09 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_viagem_data_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='data_saida',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 6, 9, 21, 16, 41, 371408, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
