# Generated by Django 5.0.4 on 2024-06-09 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_viagem_data_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='data_saida',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
