# Generated by Django 5.0.4 on 2024-06-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_viagem_data_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='data_saida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
