# Generated by Django 5.0.4 on 2024-06-13 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_suporte_desativado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='nome',
            field=models.CharField(blank=True, choices=[('Tecnico', 'Tecnico'), ('Admin', 'Admin')], default='Tecnico', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL),
        ),
    ]
