# Generated by Django 5.0.4 on 2024-06-13 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_role_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
