# Generated by Django 5.0.4 on 2024-06-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='postos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='republica',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
