# Generated by Django 5.0.4 on 2024-06-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_loja_postos_loja_republica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='postos',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='republica',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
